version: '3.7'
services:
  db:
    image: postgres:13-alpine
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: fuelPriceApp
      POSTGRES_DB: fuelPriceApp
      POSTGRES_PASSWORD: fuelPriceApp
      PG_SYSTEM_MAX_CONNECTIONS: 200
    command: ['-c', 'max_connections=200']
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - common-network

volumes:
  db-data:
  minio-data:

networks:
  common-network:
    driver: bridge
