name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  DATABASE_URL: postgresql://backend:backend@localhost:5432/backend?schema=public
  DB_PORT: 5432
jobs:
  typechecking:
    name: Typechecking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v1
        with:
          node-version: '13.14'
          registry-url: https://registry.npmjs.org/
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn
      - name: Install Prisma Client
        run: yarn prisma2 generate
      - name: Generate GraphQL Typings
        run: yarn gql:typings
      - name: Typechecking
        run: yarn typecheck
  tests:
    timeout-minutes: 5
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v1
        with:
          node-version: '12.18'
          registry-url: https://registry.npmjs.org/
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Build docker-compose stack
        run: docker-compose up -d
      - name: Install dependencies
        run: yarn
      - name: Check running containers
        run: docker ps -a
      - name: Migrations
        run: yarn prisma2 migrate up --experimental
      - name: Install Prisma Client
        run: yarn prisma2 generate
      - name: Generate GraphQL Typings
        run: yarn gql:typings
      # - name: Test
      #   run: yarn test
